alpha = 0.95
tau_H = 60.0
tau_risk = 100.0

[agree]
disjoint_metric = "jaccard_source_ids"
threshold = 0.15
false_comfort_cap = 0.05
skip_cap_pct_month = 0.05

[drift.pid]
tauH = { Kp=0.2, Ki=0.05, Kd=0.1, max=250.0 }
W_radius = { Kp=0.5, Ki=0.1, Kd=0.2, max_mult=3.0 }

[detectors]
psi_threshold = 0.15
sprt = { alpha=0.05, beta=0.2 }

[success_criteria]
cvar_improve_pct = -10.0
fn_over_baseline_abs = 0.02
far_pct_per_week_max = 2.0
pi_90d_max = 0.20
audit_sla_weeks_min_pct = 95.0

[abstain_cost]
proxy = "days_of_liberty_delayed"
normalize = true
