name: Promote latest Codex
on:
  release:
    types: [published]   # runs when you publish a release
permissions:
  contents: write        # allow commits back to the repo

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }   # get tags/history
      - name: Promote
        shell: bash
        run: |
          set -euo pipefail
          NEW_TAG="${{ github.event.release.tag_name }}"   # e.g. v1.0.16
          NEW_VER="${NEW_TAG#v}"

          # archive prior 'latest' if we know its version
          if [[ -f codex/latest/VERSION ]]; then
            PREV_VER="$(cat codex/latest/VERSION)"
            git mv codex/latest "codex/archive/v${PREV_VER}"
          fi

          # promote new version folder to latest
          rm -rf codex/latest
          mkdir -p codex/latest
          cp -a "codex/${NEW_VER}/." codex/latest/
          echo "${NEW_VER}" > codex/latest/VERSION

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Promote v${NEW_VER} → codex/latest; archive prior"
          git push
