name: Promote latest Codex
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}   # checkout a branch, not the tag
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Promote
        shell: bash
        run: |
          set -euo pipefail
          NEW_TAG="${{ github.event.release.tag_name }}"
          NEW_VER="${NEW_TAG#v}"

          PREV_VER=""
          if [[ -f codex/latest/VERSION ]]; then
            PREV_VER="$(cat codex/latest/VERSION || true)"
          fi

          if [[ -n "${PREV_VER}" ]]; then
            git mv codex/latest "codex/archive/v${PREV_VER}" || true
          fi

          rm -rf codex/latest
          mkdir -p codex/latest
          cp -a "codex/${NEW_VER}/." codex/latest/
          echo "${NEW_VER}" > codex/latest/VERSION

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Promote v${NEW_VER} ? codex/latest; archive prior v${PREV_VER}"
            git push origin "${{ github.event.repository.default_branch }}"
          fi
- name: Attach stable zip
  env:
    GH_TOKEN: ${{ github.token }}
  run: |
    cd codex/latest
    zip -r ../../UniversalCodex_latest.zip .
    cd ../..
    gh release upload "${{ github.event.release.tag_name }}" UniversalCodex_latest.zip --clobber
