name: Promote latest Codex
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - name: Promote folder and sync root README
        run: |
          set -euo pipefail
          NEW_TAG="${{ github.event.release.tag_name }}"
          NEW_VER="${NEW_TAG#v}"

          PREV_VER=""
          test -f codex/latest/VERSION && PREV_VER="$(cat codex/latest/VERSION || true)"

          if [ -n "$PREV_VER" ]; then
            git mv codex/latest "codex/archive/v${PREV_VER}" || true
          fi

          rm -rf codex/latest
          mkdir -p codex/latest
          cp -a "codex/${NEW_VER}/." codex/latest/
          echo "${NEW_VER}" > codex/latest/VERSION

          cp "codex/latest/README_Codex_v${NEW_VER}.md" README.md

          git add -A
          git diff --cached --quiet || git commit -m "Promote v${NEW_VER} -> codex/latest; sync README; archive v${PREV_VER}"
          git push
  attach-stable-zip:
    needs: promote
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: Build stable zip from codex/latest
        run: |
          cd codex/latest
          zip -r ../../UniversalCodex_latest.zip .
      - name: Upload asset to the same release
        uses: softprops/action-gh-release@v2
        with:
          files: UniversalCodex_latest.zip
